apiVersion: v2
name: bibox
description: An umbrella chart for the ecommerce microservices
type: application
version: 1.0.0
appVersion: "1.0"
dependencies:
  - name: storage-app
    version: 1.0.0
    repository: "file://charts/storage-app"
  - name: redis
    repository: https://charts.bitnami.com/bitnami
    version: 20.11.3
