mail:
  user_name: "banbao22042004@gmail.com"
  password: "${GMAIL_APP_PASSWORD}"
  mail_host: "smtp.gmail.com"
  mail_port: 587
consumer:
  worker_pool_size: 5
  brokers:
    - "kafka:9092"
  topics:
    - "user.sign_up"
  consumer_group_id: "gmail-service-group"