// Code generated by MockGen. DO NOT EDIT.
// Source: internal/common/logger/logger.go
//
// Generated by this command:
//
//	mockgen -source=internal/common/logger/logger.go -destination=test/mocks/mock_logger.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockLogger is a mock of Logger interface.
type MockLogger struct {
	ctrl     *gomock.Controller
	recorder *MockLoggerMockRecorder
	isgomock struct{}
}

// MockLoggerMockRecorder is the mock recorder for MockLogger.
type MockLoggerMockRecorder struct {
	mock *MockLogger
}

// NewMockLogger creates a new mock instance.
func NewMockLogger(ctrl *gomock.Controller) *MockLogger {
	mock := &MockLogger{ctrl: ctrl}
	mock.recorder = &MockLoggerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLogger) EXPECT() *MockLoggerMockRecorder {
	return m.recorder
}

// Debug mocks base method.
func (m *MockLogger) Debug(ctx context.Context, args map[string]any, msg string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Debug", ctx, args, msg)
}

// Debug indicates an expected call of Debug.
func (mr *MockLoggerMockRecorder) Debug(ctx, args, msg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Debug", reflect.TypeOf((*MockLogger)(nil).Debug), ctx, args, msg)
}

// Debugf mocks base method.
func (m *MockLogger) Debugf(ctx context.Context, args map[string]any, template string, format ...any) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, args, template}
	for _, a := range format {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Debugf", varargs...)
}

// Debugf indicates an expected call of Debugf.
func (mr *MockLoggerMockRecorder) Debugf(ctx, args, template any, format ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, args, template}, format...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Debugf", reflect.TypeOf((*MockLogger)(nil).Debugf), varargs...)
}

// Error mocks base method.
func (m *MockLogger) Error(ctx context.Context, args map[string]any, msg string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Error", ctx, args, msg)
}

// Error indicates an expected call of Error.
func (mr *MockLoggerMockRecorder) Error(ctx, args, msg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Error", reflect.TypeOf((*MockLogger)(nil).Error), ctx, args, msg)
}

// Errorf mocks base method.
func (m *MockLogger) Errorf(ctx context.Context, args map[string]any, template string, format ...any) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, args, template}
	for _, a := range format {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Errorf", varargs...)
}

// Errorf indicates an expected call of Errorf.
func (mr *MockLoggerMockRecorder) Errorf(ctx, args, template any, format ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, args, template}, format...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Errorf", reflect.TypeOf((*MockLogger)(nil).Errorf), varargs...)
}

// Fatal mocks base method.
func (m *MockLogger) Fatal(ctx context.Context, args map[string]any, msg string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Fatal", ctx, args, msg)
}

// Fatal indicates an expected call of Fatal.
func (mr *MockLoggerMockRecorder) Fatal(ctx, args, msg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Fatal", reflect.TypeOf((*MockLogger)(nil).Fatal), ctx, args, msg)
}

// Fatalf mocks base method.
func (m *MockLogger) Fatalf(ctx context.Context, args map[string]any, template string, format ...any) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, args, template}
	for _, a := range format {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Fatalf", varargs...)
}

// Fatalf indicates an expected call of Fatalf.
func (mr *MockLoggerMockRecorder) Fatalf(ctx, args, template any, format ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, args, template}, format...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Fatalf", reflect.TypeOf((*MockLogger)(nil).Fatalf), varargs...)
}

// Info mocks base method.
func (m *MockLogger) Info(ctx context.Context, args map[string]any, msg string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Info", ctx, args, msg)
}

// Info indicates an expected call of Info.
func (mr *MockLoggerMockRecorder) Info(ctx, args, msg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Info", reflect.TypeOf((*MockLogger)(nil).Info), ctx, args, msg)
}

// Infof mocks base method.
func (m *MockLogger) Infof(ctx context.Context, args map[string]any, template string, format ...any) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, args, template}
	for _, a := range format {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Infof", varargs...)
}

// Infof indicates an expected call of Infof.
func (mr *MockLoggerMockRecorder) Infof(ctx, args, template any, format ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, args, template}, format...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Infof", reflect.TypeOf((*MockLogger)(nil).Infof), varargs...)
}

// Panic mocks base method.
func (m *MockLogger) Panic(ctx context.Context, args map[string]any, msg string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Panic", ctx, args, msg)
}

// Panic indicates an expected call of Panic.
func (mr *MockLoggerMockRecorder) Panic(ctx, args, msg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Panic", reflect.TypeOf((*MockLogger)(nil).Panic), ctx, args, msg)
}

// Panicf mocks base method.
func (m *MockLogger) Panicf(ctx context.Context, args map[string]any, template string, format ...any) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, args, template}
	for _, a := range format {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Panicf", varargs...)
}

// Panicf indicates an expected call of Panicf.
func (mr *MockLoggerMockRecorder) Panicf(ctx, args, template any, format ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, args, template}, format...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Panicf", reflect.TypeOf((*MockLogger)(nil).Panicf), varargs...)
}

// Warn mocks base method.
func (m *MockLogger) Warn(ctx context.Context, args map[string]any, msg string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Warn", ctx, args, msg)
}

// Warn indicates an expected call of Warn.
func (mr *MockLoggerMockRecorder) Warn(ctx, args, msg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Warn", reflect.TypeOf((*MockLogger)(nil).Warn), ctx, args, msg)
}

// Warnf mocks base method.
func (m *MockLogger) Warnf(ctx context.Context, args map[string]any, template string, format ...any) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, args, template}
	for _, a := range format {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Warnf", varargs...)
}

// Warnf indicates an expected call of Warnf.
func (mr *MockLoggerMockRecorder) Warnf(ctx, args, template any, format ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, args, template}, format...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Warnf", reflect.TypeOf((*MockLogger)(nil).Warnf), varargs...)
}
