apiVersion: v2
name: email
description: An umbrella chart for the ecommerce microservices
type: application
version: 1.0.0
appVersion: "1.0" 
dependencies:
  - name: common
    version: 0.1.0
    repository: "file://../../common"


