image:
  repository: baothaihcmut/storage-app-email
  tag: v1
  pullPolicy: Always
service: {}
resources:
  requests:
    cpu: "0.25"
    memory: "128Mi"
  limits:
    cpu: "0.5"
    memory: "256Mi"
serviceAccount:
  enabled: true
  name: wait-dependency-email
  rules:
    - apiGroups: [""]
      resources: ["pods"]
      verbs: ["get", "list", "watch"]
ingressRoutes: {}

initContainers:
  - name: wait-for-dependencies
    image: bitnami/kubectl:latest
    command:
      - /bin/sh
      - -c
      - |
        echo "Waiting for Redis and Kafka to be ready..."
        kubectl wait --for=condition=Ready pod -l app=storage-app-dependency --timeout=300s
configFrom:
  fileConfigMap:
    - volumeName: config-volume
      mountPath: /app/config/config.yaml
      subPath: config.yaml
      configMap: "email"

configMap:
  name: email
  config.yaml: |
    mail:
      user_name: "banbao22042004@gmail.com"
      password: "yyof qwry hihv deqz"
      mail_host: "smtp.gmail.com"
      mail_port: 587
    consumer:
      worker_pool_size: 5
      brokers:
      - "storage-app-kafka-broker-0.storage-app-kafka-broker-headless.storage-app.svc.cluster.local:9092"
      topics:
        - "user.sign_up"
      consumer_group_id: "gmail-service-group"