server:
  port: 8080
logger:
  level: "debug"
  format: "json"
  output: "stdout"
mongo:
  uri: "mongodb+srv://thaibao22042k4:22042004bao@ecommerce-go.xbph8.mongodb.net/?retryWrites=true&w=majority&appName=ecommerce-go"
  max_pool_size: 100
  min_pool_size: 10
  connection_time_out: 30
  database: "storage-app"
jwt:
  access_token:
    secret: "your_access_secret"
    age: 3000
  refresh_token:
    secret: "your_refresh_secret"
    age: 7000
oauth2:
  client_id: "185040142880-e0o5rn2ms0d01vclb7ounj5n0i0a60he.apps.googleusercontent.com"
  secret: "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"
  redirect_uri: "http://localhost:8080/api/v1/auth/callback"
s3:
  access_key: "AKIA5FTZFI4ON633345J"
  secret_key: "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"
  region: "us-east-1"
  storage_provider: "s3"
  bucket: "storage-app-go-bucket-baothai"
