services:
  api:
    image: baothaihcmut/storage-app-api
    volumes:
      - ./config/config.yaml:/app/config/config.yaml
    labels:
      - traefik.enable=true
      - traefik.http.routers.api.rule=PathPrefix(`/api`)
      - traefik.http.routers.api.entrypoints=web
      - traefik.http.services.api.loadbalancer.server.port=8080
    networks:
      - app-network
  reverse-proxy:
    image: traefik:v2.10
    command:
      - --api.dashboard=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=reverse-proxy
      - --providers.docker=true
      - --entrypoints.web.address=:80
      - --entrypoints.dashboard.address=:8081
      - --api.insecure=true
      - --log.level=DEBUG
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 80:80
    networks:
      - app-network
      - reverse-proxy
  email-service:
    image: baothaihcmut/storage-app-email-service
    volumes:
      - ./config-email-service/config.yaml:/app/config/config.yaml
    networks:
      - app-network
networks:
  app-network:
  reverse-proxy:
    external: true
volumes:
  mongodb_data:
