services:
  api:
    image: baothaihcmut/storage-app:v1
    volumes:
      - ../config/config-storage-app.yaml:/app/config/config.yaml
    labels:
      - traefik.enable=true
      - traefik.http.routers.api.rule=PathPrefix(`/api`)
      - traefik.http.routers.api.entrypoints=web
      - traefik.http.services.api.loadbalancer.server.port=8080
    networks:
      - app-network
    restart: always
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 256M
        reservations:
          cpus: "0.5"
          memory: 128M

  reverse-proxy:
    image: traefik:v2.10
    command:
      - --api.dashboard=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=reverse-proxy
      - --providers.docker=true
      - --entrypoints.web.address=:80
      - --entrypoints.dashboard.address=:8081
      - --api.insecure=true
      - --log.level=DEBUG
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8080:80
    networks:
      - app-network
      - reverse-proxy
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 256M
        reservations:
          cpus: "0.5"
          memory: 128M
  email-service:
    image: baothaihcmut/storage-app-email:v1
    volumes:
      - ../config/config-email-service.yaml:/app/config/config.yaml
    networks:
      - app-network
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 256M
        reservations:
          cpus: "0.5"
          memory: 128M
networks:
  app-network:
    external: true
  reverse-proxy:
    external: true