version: "3.8"

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ../prometheus/prometheus.yaml:/etc/prometheus/prometheus.yaml
    command:
      - "--config.file=/etc/prometheus/prometheus.yaml"
    restart: unless-stopped
    networks:
      - app-network
      - monitor-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER_NAME}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
    volumes:
      - grafana-storage:/var/lib/grafana
    restart: unless-stopped
    networks:
      - monitor-network
    labels:
      - traefik.enable=true
      - traefik.http.routers.api.rule=PathPrefix(`/monitor`)
      - traefik.http.routers.api.entrypoints=web
      - traefik.http.services.api.loadbalancer.server.port=3000
      - traefik.http.middlewares.grafana-strip.stripprefix.prefixes=/monitor
      - traefik.http.routers.grafana.middlewares=grafana-strip

volumes:
  grafana-storage:
    driver: local
networks:
  app-network:
    external: true
  monitor-network:
