services:
  redis:
    image: redis:latest
    container_name: redis-server
    restart: always
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]
    networks:
      - app-network

volumes:
  redis_data:
networks:
  app-network:
    external: true
