// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/confirm": {
            "post": {
                "description": "Confirm sign up",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "parameters": [
                    {
                        "description": "code for confirm",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/presenter.ConfirmSignUpInput"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Confirm sign up success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.AppResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/presenter.ConfirmSignUpOutput"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "Invalid confirm code",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.AppResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/auth/exchange": {
            "post": {
                "description": "Exchange Google auth code",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "parameters": [
                    {
                        "description": "auth code from google oauth2 resposne",
                        "name": "authCode",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/presenter.ExchangeTokenInput"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Login success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.AppResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "Wrong auth code",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.AppResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/auth/log-in": {
            "post": {
                "description": "Log in",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "parameters": [
                    {
                        "description": "information for log in",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/presenter.LogInInput"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Login success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.AppResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "Wrong password or email",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.AppResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/auth/sign-up": {
            "post": {
                "description": "Sign up",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "parameters": [
                    {
                        "description": "information for sign up",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/presenter.SignUpInput"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Sign up success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.AppResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/presenter.SignUpOutput"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "409": {
                        "description": "Email exist, email is pending for cofirm",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.AppResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/files/:id/download-url": {
            "get": {
                "description": "Get download url of file",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "files"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "file id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "preview mode",
                        "name": "preview",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Find tags of file sucess",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.AppResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/presenters.GetFileDownloadUrlOutput"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "miss id",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.AppResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "403": {
                        "description": "permission denied",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.AppResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "404": {
                        "description": "file not found",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.AppResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "409": {
                        "description": "file is folder",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.AppResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/files/:id/metadata": {
            "get": {
                "description": "Get metadata of file",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "files"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "file id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Find tags of file sucess",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.AppResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/presenters.GetFileMetaDataOuput"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "miss id",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.AppResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "403": {
                        "description": "permission denied",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.AppResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "404": {
                        "description": "file not found",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.AppResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/files/:id/permissions": {
            "get": {
                "description": "Get permission of file",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "files"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "file id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Find tags of file sucess",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.AppResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/presenters.GetFilePermissionOuput"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "miss id",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.AppResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "403": {
                        "description": "permission denied",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.AppResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "404": {
                        "description": "file not found",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.AppResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/files/:id/permissions/add": {
            "post": {
                "description": "Add permission for file",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "files"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "file id must be UUID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "permission info",
                        "name": "file",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/presenters.AddFilePermissionInput"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Add permission success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.AppResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/presenters.AddFilePermissionOutput"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "403": {
                        "description": "User don't have permission for this file operation",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.AppResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "404": {
                        "description": "Parent folder not found, Tag of file not found",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.AppResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/files/:id/sub-file": {
            "get": {
                "description": "Find file of user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "files"
                ],
                "parameters": [
                    {
                        "type": "boolean",
                        "description": "file is folder or not, if null fetch all file and folder",
                        "name": "is_folder",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "sort field, allow short field: created_at, updated_at, opened_at",
                        "name": "sort_by",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "boolean",
                        "description": "sort direction",
                        "name": "is_asc",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "for pagination",
                        "name": "offset",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "for pagination",
                        "name": "limit",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "mime type of file, if is_folder is true not pass mime_type",
                        "name": "mime_type",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "file id",
                        "name": "id",
                        "in": "path"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Find file of user sucess",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.AppResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/presenters.GetSubFileOfFolderInput"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Unallow sort field, lack of query",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.AppResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/files/:id/tags": {
            "get": {
                "description": "Get tag of file",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "files"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "file id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Find tags of file sucess",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.AppResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/presenters.GetFileTagsOutput"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "miss id",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.AppResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "403": {
                        "description": "permission denied",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.AppResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "404": {
                        "description": "file not found",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.AppResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/files/:id/uploaded": {
            "patch": {
                "description": "Uploaded file",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "files"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "file id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Uploaded file sucess",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.AppResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/presenters.UploadedFileOutput"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "403": {
                        "description": "file is folder",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.AppResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "404": {
                        "description": "file not found",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.AppResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/files/add": {
            "post": {
                "description": "Create new file 111",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "files"
                ],
                "parameters": [
                    {
                        "description": "file information",
                        "name": "file",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/presenters.CreateFileInput"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Create file sucess, storage_detail.put_object_url is presign url for upload file",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.AppResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/presenters.CreateFileOutput"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "403": {
                        "description": "User don't have permission for this file operation",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.AppResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "404": {
                        "description": "Parent folder not found, Tag of file not found",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.AppResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/files/my-drive": {
            "get": {
                "description": "Find file of user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "files"
                ],
                "parameters": [
                    {
                        "type": "boolean",
                        "description": "file is in other folder, if null fetch all file",
                        "name": "is_in_folder",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "file is folder or not, if null fetch all file and folder",
                        "name": "is_folder",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "sort field, allow short field: created_at, updated_at, opened_at",
                        "name": "sort_by",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "boolean",
                        "description": "sort direction",
                        "name": "is_asc",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "for pagination",
                        "name": "offset",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "for pagination",
                        "name": "limit",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "mime type of file, if is_folder is true not pass mime_type",
                        "name": "mime_type",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Find file of user sucess",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.AppResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/presenters.FindFileOfUserOuput"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Un allow sort field, lack of query",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.AppResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/files/upload-folder": {
            "post": {
                "description": "upload folder",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "files"
                ],
                "parameters": [
                    {
                        "description": "folder information",
                        "name": "file",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/presenters.UploadFolderInput"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Create file sucess, storage_detail.put_object_url is presign url for upload file",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.AppResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/presenters.UploadFolderOutput"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "403": {
                        "description": "User don't have permission for this file operation",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.AppResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "404": {
                        "description": "Parent folder not found, Tag of file not found",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.AppResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/users/search": {
            "get": {
                "description": "search user by email",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "email value can be any string",
                        "name": "email",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "off set must be greater than 0",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "limit must be greater than 0",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "201": {
                        "description": "search user success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.AppResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/presenters.SearchUserOuput"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "enums.FileFilePermissionType": {
            "type": "integer",
            "enum": [
                1,
                2,
                3
            ],
            "x-enum-varnames": [
                "ViewPermission",
                "CommentPermission",
                "EditPermission"
            ]
        },
        "enums.MimeType": {
            "type": "string",
            "enum": [
                "image/jpeg",
                "image/png",
                "image/gif",
                "image/bmp",
                "image/webp",
                "image/tiff",
                "image/svg+xml",
                "application/pdf",
                "application/msword",
                "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
                "application/vnd.ms-excel",
                "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
                "application/vnd.ms-powerpoint",
                "application/vnd.openxmlformats-officedocument.presentationml.presentation",
                "text/plain",
                "text/csv",
                "application/json",
                "application/xml",
                "application/x-yaml",
                "audio/mpeg",
                "audio/wav",
                "audio/ogg",
                "audio/flac",
                "audio/aac",
                "video/mp4",
                "video/webm",
                "video/x-msvideo",
                "video/quicktime",
                "video/x-matroska",
                "application/zip",
                "application/vnd.rar",
                "application/x-7z-compressed",
                "application/x-tar",
                "application/gzip",
                "text/html",
                "text/css",
                "application/javascript",
                "text/x-go",
                "text/x-python",
                "application/x-sh",
                "application/x-msdownload",
                "application/octet-stream"
            ],
            "x-enum-varnames": [
                "MimeJPG",
                "MimePNG",
                "MimeGIF",
                "MimeBMP",
                "MimeWEBP",
                "MimeTIFF",
                "MimeSVG",
                "MimePDF",
                "MimeDOC",
                "MimeDOCX",
                "MimeXLS",
                "MimeXLSX",
                "MimePPT",
                "MimePPTX",
                "MimeTXT",
                "MimeCSV",
                "MimeJSON",
                "MimeXML",
                "MimeYAML",
                "MimeMP3",
                "MimeWAV",
                "MimeOGG",
                "MimeFLAC",
                "MimeAAC",
                "MimeMP4",
                "MimeWebM",
                "MimeAVI",
                "MimeMOV",
                "MimeMKV",
                "MimeZIP",
                "MimeRAR",
                "Mime7z",
                "MimeTAR",
                "MimeGZIP",
                "MimeHTML",
                "MimeCSS",
                "MimeJS",
                "MimeGo",
                "MimePython",
                "MimeShell",
                "MimeEXE",
                "MimeBIN"
            ]
        },
        "enums.FilePermissionType": {
            "type": "integer",
            "enum": [
                1,
                3,
                5
            ],
            "x-enum-varnames": [
                "FilePermissionTypeView",
                "FilePermissionTypeComment",
                "PermissionEdit"
            ]
        },
        "presenter.ConfirmSignUpInput": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                }
            }
        },
        "presenter.ConfirmSignUpOutput": {
            "type": "object"
        },
        "presenter.ExchangeTokenInput": {
            "type": "object",
            "properties": {
                "auth_code": {
                    "type": "string"
                },
                "provider": {
                    "type": "integer",
                    "maximum": 2,
                    "minimum": 1
                }
            }
        },
        "presenter.LogInInput": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "presenter.SignUpInput": {
            "type": "object",
            "required": [
                "first_name",
                "last_name",
                "password",
                "repeat_password"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "first_name": {
                    "type": "string"
                },
                "last_name": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "repeat_password": {
                    "type": "string"
                }
            }
        },
        "presenter.SignUpOutput": {
            "type": "object"
        },
        "presenters.AddFilePermissionInput": {
            "type": "object",
            "properties": {
                "fileId": {
                    "type": "string"
                },
                "permissions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/presenters.FilePermission"
                    }
                }
            }
        },
        "presenters.AddFilePermissionOutput": {
            "type": "object",
            "properties": {
                "permissions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/presenters.FilePermissionOuput"
                    }
                }
            }
        },
        "presenters.AdditionFilePermission": {
            "type": "object",
            "required": [
                "file_id",
                "permission_type"
            ],
            "properties": {
                "file_id": {
                    "type": "string"
                },
                "permission_type": {
                    "$ref": "#/definitions/enums.FileFilePermissionType"
                }
            }
        },
        "presenters.CreateFileInput": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "description": {
                    "type": "string"
                },
                "is_folder": {
                    "description": "Use *bool to allow nil check",
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "parent_folder_id": {
                    "type": "string"
                },
                "storage_detail": {
                    "type": "object",
                    "required": [
                        "mime_type",
                        "size"
                    ],
                    "properties": {
                        "mime_type": {
                            "description": "Required field",
                            "type": "string"
                        },
                        "size": {
                            "description": "Required field",
                            "type": "integer"
                        }
                    }
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "presenters.CreateFileOutput": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "is_folder": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "opened_at": {
                    "type": "string"
                },
                "owner_id": {
                    "type": "string"
                },
                "parent_folder_id": {
                    "type": "string"
                },
                "put_object_url": {
                    "type": "string"
                },
                "storage_detail": {
                    "$ref": "#/definitions/presenters.StorageDetailOuput"
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "total_size": {
                    "type": "integer"
                },
                "updated_at": {
                    "type": "string"
                },
                "url_expiry": {
                    "type": "integer"
                }
            }
        },
        "presenters.FilePermission": {
            "type": "object",
            "required": [
                "user_id"
            ],
            "properties": {
                "addition_permissions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/presenters.AdditionFilePermission"
                    }
                },
                "permission_type": {
                    "$ref": "#/definitions/enums.FilePermissionType"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "presenters.FilePermissionOuput": {
            "type": "object",
            "properties": {
                "access_secure_file": {
                    "type": "boolean"
                },
                "can_share": {
                    "type": "boolean"
                },
                "file_id": {
                    "type": "string"
                },
                "permission_type": {
                    "$ref": "#/definitions/enums.FileFilePermissionType"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "presenters.FilePermissionUserInfo": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "first_name": {
                    "type": "string"
                },
                "image": {
                    "type": "string"
                },
                "last_name": {
                    "type": "string"
                }
            }
        },
        "presenters.FilePermssionWithUserOutput": {
            "type": "object",
            "properties": {
                "access_secure_file": {
                    "type": "boolean"
                },
                "can_share": {
                    "type": "boolean"
                },
                "file_id": {
                    "type": "string"
                },
                "permission_type": {
                    "$ref": "#/definitions/enums.FileFilePermissionType"
                },
                "user": {
                    "$ref": "#/definitions/presenters.FilePermissionUserInfo"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "presenters.FileWithPathOutput": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "is_folder": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "opened_at": {
                    "type": "string"
                },
                "owner_id": {
                    "type": "string"
                },
                "parent_folder_id": {
                    "type": "string"
                },
                "path": {
                    "type": "string"
                },
                "put_object_url": {
                    "type": "string"
                },
                "storage_detail": {
                    "$ref": "#/definitions/presenters.StorageDetailOuput"
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "total_size": {
                    "type": "integer"
                },
                "updated_at": {
                    "type": "string"
                },
                "url_expiry": {
                    "type": "integer"
                }
            }
        },
        "presenters.FileWithPermissionOutput": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "is_folder": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "opened_at": {
                    "type": "string"
                },
                "owner_id": {
                    "type": "string"
                },
                "parent_folder_id": {
                    "type": "string"
                },
                "permission_type": {
                    "$ref": "#/definitions/enums.FileFilePermissionType"
                },
                "permissions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/presenters.PermissionOfFileOuput"
                    }
                },
                "storage_detail": {
                    "$ref": "#/definitions/presenters.StorageDetailOuput"
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "total_size": {
                    "type": "integer"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "presenters.FindFileOfUserOuput": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/presenters.FileWithPermissionOutput"
                    }
                },
                "pagination": {
                    "$ref": "#/definitions/response.PaginationResponse"
                }
            }
        },
        "presenters.GetFileDownloadUrlOutput": {
            "type": "object",
            "properties": {
                "content_type": {
                    "$ref": "#/definitions/enums.MimeType"
                },
                "expiry": {
                    "type": "integer"
                },
                "file_name": {
                    "type": "string"
                },
                "method": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "presenters.GetFileMetaDataOuput": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "is_folder": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "opened_at": {
                    "type": "string"
                },
                "owner_id": {
                    "type": "string"
                },
                "parent_folder_id": {
                    "type": "string"
                },
                "storage_detail": {
                    "$ref": "#/definitions/presenters.StorageDetailOuput"
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "total_size": {
                    "type": "integer"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "presenters.GetFilePermissionOuput": {
            "type": "object",
            "properties": {
                "permissions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/presenters.FilePermssionWithUserOutput"
                    }
                }
            }
        },
        "presenters.GetFileTagsOutput": {
            "type": "object",
            "properties": {
                "tags": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/presenters.TagOutput"
                    }
                }
            }
        },
        "presenters.GetSubFileOfFolderInput": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "is_asc": {
                    "type": "boolean"
                },
                "is_folder": {
                    "type": "boolean"
                },
                "limit": {
                    "type": "integer"
                },
                "mime_type": {
                    "type": "string"
                },
                "offset": {
                    "type": "integer"
                },
                "sort_by": {
                    "type": "string"
                }
            }
        },
        "presenters.PermissionOfFileOuput": {
            "type": "object",
            "properties": {
                "permission_type": {
                    "$ref": "#/definitions/enums.FileFilePermissionType"
                },
                "user_id": {
                    "type": "string"
                },
                "user_image": {
                    "type": "string"
                }
            }
        },
        "presenters.SearchUserOuput": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/presenters.UserOutput"
                    }
                },
                "pagination": {
                    "$ref": "#/definitions/response.PaginationResponse"
                }
            }
        },
        "presenters.StorageDetailOuput": {
            "type": "object",
            "properties": {
                "file_size": {
                    "type": "integer"
                },
                "mime_type": {
                    "$ref": "#/definitions/enums.MimeType"
                }
            }
        },
        "presenters.TagOutput": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "presenters.UploadFolderInput": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/presenters.CreateFileInput"
                },
                "sub_files": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/presenters.UploadFolderInput"
                    }
                }
            }
        },
        "presenters.UploadFolderOutput": {
            "type": "object",
            "properties": {
                "files": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/presenters.FileWithPathOutput"
                    }
                }
            }
        },
        "presenters.UploadedFileOutput": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "is_folder": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "opened_at": {
                    "type": "string"
                },
                "owner_id": {
                    "type": "string"
                },
                "parent_folder_id": {
                    "type": "string"
                },
                "storage_detail": {
                    "$ref": "#/definitions/presenters.StorageDetailOuput"
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "total_size": {
                    "type": "integer"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "presenters.UserOutput": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "first_name": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "image": {
                    "type": "string"
                },
                "last_name": {
                    "type": "string"
                }
            }
        },
        "response.AppResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "sucess": {
                    "type": "boolean"
                }
            }
        },
        "response.PaginationResponse": {
            "type": "object",
            "properties": {
                "has_next": {
                    "type": "boolean"
                },
                "has_prev": {
                    "type": "boolean"
                },
                "limit": {
                    "type": "integer"
                },
                "next_offset": {
                    "type": "integer"
                },
                "offset": {
                    "type": "integer"
                },
                "prev_offset": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Storage App API",
	Description:      "This is a sample API for file storage",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
