server:
  port: 8080
logger:
  level: "debug"
  format: "json"
  output: "stdout"
mongo:
  uri: "mongodb+srv://thaibao22042k4:<db_password>@ecommerce-go.xbph8.mongodb.net/?retryWrites=true&w=majority&appName=ecommerce-go"
  min_pool_size: 10
  connection_time_out: 30
  database: "storage-app"
jwt:
  access_token:
    secret: ${JWT_ACCESS_SECRET}
    age: 3000
  refresh_token:
    secret: ${JWT_REFRESH_SECRET}
    age: 7000
oauth2:
  client_id: ${OAUTH2_CLIENT_ID}
  secret: ${OAUTH2_SECRET}
  redirect_uri: "http://0/api/v1/auth/callback"
s3:
  access_key: ${S3_ACCESS_KEY}
  secret_key: ${S3_SECRET_KEY}
  region: "us-elocalhost:808ast-1"
  storage_provider: "s3"
  bucket: "storage-app-go-bucket-baothai"
