listeners:
  securityProtocolMap: "CONTROLLER:SASL_PLAINTEXT,CLIENT:SASL_PLAINTEXT,INTERNAL:SASL_PLAINTEXT"
sasl:
  interbroker:
    user: "kafka-interbroker"
    password: "kafka-interbroker-password"
  controller:
    user: "kafka-controller"
    password: "kafka-controller-password"
  client:
    users:
      - "kafka-client-1"
    password:
      - "kafka-client-1-password"

clusterId: "X9cTw1P0QfGpULyY4lT-tg"
controller:
  replicaCount: 1
  persistence:
    storageClass: "local-path"

broker:
  replicaCount: 1
  persistence:
    storageClass: "local-path"
  extraEnvVars:
    - name: BITNAMI_DEBUG
      value: "true"


