sasl:
  interbroker:
    user: "kafka-interbroker"
    password: "kafka-interbroker-password"
  controller:
    user: "kafka-controller"
    password: "kafka-controller-password"
  client:
    users:
      - "kafka-client-1"
    password:
      - "kafka-client-1-password"

controller:
  replicaCount: 2
  persistence:
    storageClass: "local-path"