architecture: replication
auth:
  enabled: true
  sentinel: true
  password: "redispassword"
master:
  count: 1
  persistence:
    storageClass: "local-path"
    size: "500Mi"

replica:
  replicaCount: 3
  persistence:
    storageClass: "local-path"
    size: "500Mi"
sentinel:
  enabled: true
  quorum: 2
  persistence:
    storageClass: "local-path"
    size: "500Mi"