apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-config-map
  namespace: storage-app
data:
  KAFKA_BROKER_ID: "1"
  KAFKA_ZOOKEEPER_CONNECT: zookeeper-statefulset-0.zookeeper-headless.storage-app.svc.cluster.local:2181
  KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-statefulset-0.kafka-headless.storage-app.svc.cluster.local:9092
  KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
  KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
  KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
  KAFKA_CLUSTER_ID: "eoh_OotURgmz6zPQVDjOjQ"