apiVersion: v1
kind: Service
metadata:
  name: zookeeper-headless
  namespace: storage-app
  labels:
    app: zookeeper
spec:
  clusterIP: None  
  selector:
    app: zookeeper
  ports:
    - name: client
      port: 2181
      targetPort: client