apiVersion: v1
kind: ConfigMap
metadata:
  name: storage-app-config
  namespace: storage-app
data:
  config.yaml: |
    server:
      port: 8080
    logger:
      level: "debug"
      format: "json"
      output: "stdout"
    mongo:
      uri: "mongodb+srv://thaibao22042k4:22042004bao@ecommerce-go.xbph8.mongodb.net/?retryWrites=true&w=majority&appName=ecommerce-go"
      max_pool_size: 100
      min_pool_size: 10
      connection_time_out: 30
      database: "storage-app"
    jwt:
      access_token:
        secret: "your_access_secret"
        age: 3000
      refresh_token:
        secret: "your_refresh_secret"
        age: 7000
    oauth2:
      google:
        client_id: "185040142880-e0o5rn2ms0d01vclb7ounj5n0i0a60he.apps.googleusercontent.com"
        secret: "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"
        redirect_uri: "http://localhost:8080/api/v1/auth/callback"
      github:
        client_id: "Ov23liJ3ADLrxMEn5M9o"
        secret: "7ad93def9688d2a897a5fc7c9e0cdb7bc8089caf"
        redirect_uri: "http://localhost:8080/api/v1/auth/callback"
    s3:
      access_key: "AKIA5FTZFI4OKLHKBITV"
      secret_key: "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"
      region: "us-east-1"
      storage_provider: "s3"
      bucket: "storage-app-go-bucket-baothai"

    redis:
      endpoint: "14.225.253.242:6379"
      database: 0
      user_name: "" 
      password: ""

    kafka:
      brokers:
        - "14.225.253.242:9092"
      max_retry: 10