apiVersion: apps/v1
kind: Deployment
metadata:
  name: storage-app-deployment
  namespace: storage-app
  labels:
    app: storage-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: storage-app
  template:
    metadata:
      labels:
        app: storage-app
    spec:
      imagePullSecrets:
      - name: my-registry-secret
      containers:
      - name: storage-app
        image: baothaihcmut/storage-app:v1
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - name: config-volume
            mountPath: /app/config/config.yaml
            subPath: config.yaml
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
      restartPolicy: Always
      volumes: 
        - name: config-volume
          configMap:
            name: storage-app-config


