apiVersion: v1
kind: Service
metadata:
  name: storage-app-svc
  namespace: storage-app
spec:
  selector:
    app: storage-app  
  ports:
    - protocol: TCP
      port: 80        
      targetPort: 8080 
  type: ClusterIP  
