name: Storage app service CI/CD

on:
  push:
    paths:
      - "storage-app/**"
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21

      - name: Run Linter
        run: |
          cd storage-app
          go install golang.org/x/lint/golint@latest
          golint ./...

  build:
    runs-on: ubuntu-lastest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name:  Set up go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.2
      
      - name: Build bin
        run: |
          cd storage-app
          CGO_ENABLED=0
          GOOS=linux 
          GOARCH=amd64 
          go build -o bin/storage-app cmd/storage-app/main.go
      
      - name: Push to artifact 
        uses: actions/upload-artifact@v4
        with:
          name: storage-app
          path: storage-app/bin/storage-app
      
  test:
    runs-on: ubuntu-lastest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      
      - name:  Set up go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.2
      
      - name: Run test
        run: |
          cd storage-app/test
          go test ./... -v -coverprofile=coverage.out 
      
  build-image:
    needs: build
    runs-on: ubuntu-lastest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: storage-app
          path: .
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

       - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./storage-app 
          file: ./storage-app/Dockerfile  
          push: true
          tags: |
            baothaihcmut/storage-app:lastest
      
        



    



      