name: Storage app service CI/CD

on:
  push:
    paths:
      - "storage-app/**"
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21

      - name: Run Linter
        run: |
          cd storage-app
          go install golang.org/x/lint/golint@latest
          golint ./...
        
      