name: Helm chart Storage app CI/CD

on:
  push:
    paths:
      - "environments/helm/apps/storage-app/**"
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Copy config file to server
        run: |
          export MONGO_URI="${{ secrets.MONGO_URI }}"
          export JWT_ACCESS_TOKEN_SECRET="${{ secrets.JWT_ACCESS_TOKEN_SECRET }}"
          export JWT_REFRESH_TOKEN_SECRET="${{ secrets.JWT_REFRESH_TOKEN_SECRET }}"
          export GOOGLE_OAUTH2_CLIENT_ID="${{ secrets.GOOGLE_OAUTH2_CLIENT_ID }}"
          export GOOGLE_OAUTH2_SECRET="${{ secrets.GOOGLE_OAUTH2_SECRET }}"
          export OAUTH2_CLIENT_ID="${{ secrets.OAUTH2_CLIENT_ID }}"
          export OAUTH2_SECRET="${{ secrets.OAUTH2_SECRET }}"
          export S3_ACCESS_KEY="${{ secrets.S3_ACCESS_KEY }}"
          export S3_SECRET_KEY="${{ secrets.S3_SECRET_KEY }}"
          export GOOGLE_OAUTH2_REDIRECT_URI="$GOOGLE_OAUTH2_REDIRECT_URI"
          export GMAIL_APP_PASSWORD="${{ secrets.GMAIL_APP_PASSWORD }}"
          envsubst < environments/helm/storage-app/values.yaml > environments/helm/storage-app/values.env.yaml
      - name: 'Deploy'
        uses: 'deliverybot/helm@v1'
        with:
          release: 'storage-app'
          namespace: 'storage-app'
          chart: 'environments/helm/storage-app'
          token: '${{ github.token }}'
          value-files: >-
          [
            "environments/helm/storage-app/values.env.yaml"
          ]
        env:
          KUBECONFIG_FILE: '${{ secrets.KUBECONFIG }}'


