name: Storage app service CI/CD

on:
  push:
    paths:
      - "storage-app/**"
      - ".github/workflows/**"
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.2

      - name: Install golangci-lint
        run: |
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

      - name: Run Linter
        run: |
          cd storage-app
          golangci-lint run ./...

  build:
    needs: docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.2

      - name: Install Swag
        run: |
          go install github.com/swaggo/swag/cmd/swag@latest
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

      - name: Generate Swagger docs
        run: |
          cd storage-app
          swag init -g ./cmd/storage-app/main.go --output ./docs

          
      - name: Build bin
        run: |
          cd storage-app
          export CGO_ENABLED=0 GOOS=linux GOARCH=amd64
          go build -o bin/storage-app cmd/storage-app/main.go

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: storage-app
          path: storage-app/bin/storage-app

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.2

      - name: Run tests
        run: |
          cd storage-app/test
          go test ./... -v -coverprofile=coverage.out

  build-image:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: storage-app
          path: storage-app/bin/

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./storage-app
          file: ./storage-app/Dockerfile
          push: true
          tags: |
            baothaihcmut/storage-app:latest
  
  deploy:
    needs: build-image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
      - name: Copy config file to server
        run: |
          export MONGO_URI="${{ secrets.MONGO_URI }}"
          export JWT_ACCESS_TOKEN_SECRET="${{ secrets.JWT_ACCESS_TOKEN_SECRET }}"
          export JWT_REFRESH_TOKEN_SECRET="${{ secrets.JWT_REFRESH_TOKEN_SECRET }}"
          export GOOGLE_OAUTH2_CLIENT_ID="${{ secrets.GOOGLE_OAUTH2_CLIENT_ID }}"
          export GOOGLE_OAUTH2_SECRET="${{ secrets.GOOGLE_OAUTH2_SECRET }}"
          export OAUTH2_CLIENT_ID="${{ secrets.OAUTH2_CLIENT_ID }}"
          export OAUTH2_SECRET="${{ secrets.OAUTH2_SECRET }}"
          export S3_ACCESS_KEY="${{ secrets.S3_ACCESS_KEY }}"
          export S3_SECRET_KEY="${{ secrets.S3_SECRET_KEY }}"
          export GOOGLE_OAUTH2_REDIRECT_URI="$GOOGLE_OAUTH2_REDIRECT_URI"
          export GMAIL_APP_PASSWORD="${{ secrets.GMAIL_APP_PASSWORD }}"
          mkdir config
          envsubst < environments/config/config-storage-app-template.yaml > config/config-storage-app.yaml
          envsubst < environments/config/config-email-service-template.yaml > config/config-email-service.yaml
          scp -r ./config ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:~/storage-app
          scp -r environments/docker ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:~/storage-app

      - name: Deploy
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
              cd storage-app/docker
              # Restart services
              docker compose -f docker-compose-api.yaml pull
              docker compose -f docker-compose-api.yaml up -d 
              docker compose -f docker-compose-kafka.yaml up -d
              docker compose -f docker-compose-redis.yaml up -d
 

